pipeline {
    agent any

    stages {
        stage('install requirements') {
            steps {
                sh '''
                env.JENKINS_HOME = ./PullRequest
                pip install -r requirements.txt --break-system-packages
                '''
            }
        }
        stage('check code') {
            steps {
                sh '''
                python3 -m pylint test_file.py
                '''
            }
        }
        stage('build') {
            steps {
                sh '''
                python3 test_file.py
                '''
            }
        }
        stage('TestAPI') {
            steps {
                sh '''
                python3 -m pytest
                '''
            }
        }
        /*stage('build container') {
            agent {
                docker { image 'node:20.11.0-alpine3.19' }
            }
            steps {
                sh '''
                python3 test_file.py
                '''
            }
        }*/
    }
}
